/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccessCriteriaSection: typeof import('./src/components/negotiation-tabs/AccessCriteriaSection.vue')['default']
    AddResourcesButton: typeof import('./src/components/AddResourcesButton.vue')['default']
    AddResourcesModal: typeof import('./src/components/modals/AddResourcesModal.vue')['default']
    Alert: typeof import('./src/components/AlertNotification.vue')['default']
    AlertNotification: typeof import('./src/components/AlertNotification.vue')['default']
    BAvatar: typeof import('bootstrap-vue-next')['BAvatar']
    ConfirmationModal: typeof import('./src/components/modals/ConfirmationModal.vue')['default']
    CopyTextButton: typeof import('./src/components/CopyTextButton.vue')['default']
    FeedbackModal: typeof import('./src/components/modals/FeedbackModal.vue')['default']
    FilterSort: typeof import('./src/components/FilterSort.vue')['default']
    Footer: typeof import('./src/components/FooterComp.vue')['default']
    FooterComp: typeof import('./src/components/FooterComp.vue')['default']
    FormSubmissionModal: typeof import('./src/components/modals/FormSubmissionModal.vue')['default']
    FormViewModal: typeof import('./src/components/modals/FormViewModal.vue')['default']
    GoBackButton: typeof import('./src/components/GoBackButton.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    NegotiationAttachment: typeof import('./src/components/NegotiationAttachment.vue')['default']
    NegotiationCard: typeof import('./src/components/NegotiationCard.vue')['default']
    NegotiationForm: typeof import('./src/components/NegotiationForm.vue')['default']
    NegotiationList: typeof import('./src/components/NegotiationList.vue')['default']
    NegotiationOrganizationCard: typeof import('./src/components/NegotiationOrganizationCard.vue')['default']
    NegotiationPagination: typeof import('./src/components/NegotiationPagination.vue')['default']
    NegotiationPosts: typeof import('./src/components/NegotiationPosts.vue')['default']
    NegotiatorModal: typeof import('./src/components/modals/NegotiatorModal.vue')['default']
    NetworkSelect: typeof import('./src/components/NetworkSelect.vue')['default']
    NewRequestButton: typeof import('./src/components/NewRequestButton.vue')['default']
    NewRequestModal: typeof import('./src/components/modals/NewRequestModal.vue')['default']
    Notifications: typeof import('./src/components/NotificationsButton.vue')['default']
    NotificationsButton: typeof import('./src/components/NotificationsButton.vue')['default']
    OidcCallback: typeof import('./src/components/OidcCallback.vue')['default']
    PDFButton: typeof import('./src/components/PDFButton.vue')['default']
    PrivatePostModal: typeof import('./src/components/modals/PrivatePostModal.vue')['default']
    ProfileSettings: typeof import('./src/components/ProfileSettings.vue')['default']
    ResourcesList: typeof import('./src/components/ResourcesList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiConfigurationSetting: typeof import('./src/components/UiConfigurationSetting.vue')['default']
    VueTour: typeof import('./src/components/VueTour.vue')['default']
  }
}
