const dateFormat = "LL - LT"

const ROLES = {
  RESEARCHER: "RESEARCHER",
  REPRESENTATIVE: "REPRESENTATIVE",
  ADMINISTRATOR: "ADMIN"
}

const MESSAGE_STATUS = {
  SENT: "CREATED",
  READ: "READ"
}


export { MESSAGE_STATUS, ROLES, dateFormat }