version: '3'
services:
  oidc-server-mock:
    container_name: oidc-server-mock
    image: ghcr.io/soluto/oidc-server-mock:latest
    ports:
      - '4011:80'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_OPTIONS_INLINE: |
        {
          "AccessTokenJwtType": "JWT",
          "Discovery": {
            "ShowKeySet": true
          },
          "Authentication": {
            "CookieSameSiteMode": "Lax",
            "CheckSessionCookieSameSiteMode": "Lax"
          }
        }
      LOGIN_OPTIONS_INLINE: |
        {
          "AllowRememberLogin": false
        }
      LOGOUT_OPTIONS_INLINE: |
        {
          "AutomaticRedirectAfterSignOut": true
        }
      IDENTITY_RESOURCES_PATH: /config/identity-resources.json
      USERS_CONFIGURATION_INLINE: |
        [
          {
            "SubjectId":"1000@bbmri.eu",
            "Username":"Researcher",
            "Password":"researcher",
            "Claims": [
              {
                "Type": "name",
                "Value": "Adam Researcher",
                "ValueType": "string"
              },
              {
                "Type": "given_name",
                "Value": "Adam",
                "ValueType": "string"
              },
              {
                "Type": "family_name",
                "Value": "Researcher",
                "ValueType": "string"
              },
              {
                "Type": "preferred_username",
                "Value": "TheResearcher",
                "ValueType": "string"
              },
              {
                "Type": "email",
                "Value": "adam.researcher@gmail.com",
                "ValueType": "string"
              },
              {
                "Type": "eduperson_entitlement",
                "Value": "[\"urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:researchers#perun.bbmri-eric.eu\"]",
                "ValueType": "json"
              }
            ]
          },
          {
            "SubjectId":"1001@bbmri.eu",
            "Username":"Biobanker",
            "Password":"biobanker",
            "Claims": [
              {
                "Type": "name",
                "Value": "Taylor Biobanker",
                "ValueType": "string"
              },
              {
                "Type": "given_name",
                "Value": "Taylor",
                "ValueType": "string"
              },
              {
                "Type": "family_name",
                "Value": "Biobanker",
                "ValueType": "string"
              },
              {
                "Type": "preferred_username",
                "Value": "TheBiobanker",
                "ValueType": "string"
              },
              {
                "Type": "email",
                "Value": "taylor.biobanker@gmail.com",
                "ValueType": "string"
              },
              {
                "Type": "eduperson_entitlement",
                "Value": "[\"urn:geant:bbmri-eric.eu:group:bbmri:collections:BBMRI-ERIC%20Directory#perun.bbmri-eric.eu\", \"urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:researchers#perun.bbmri-eric.eu\", \"urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:biobankers#perun.bbmri-eric.eu\", \"urn:geant:bbmri-eric.eu:group:bbmri:collections:BBMRI-ERIC%20Directory:bbmri-eric.ID.SE_890.collection.dummy_collection#perun.bbmri-eric.eu\", \"urn:geant:bbmri-eric.eu:group:bbmri:collections:BBMRI-ERIC%20Directory:bbmri-eric.ID.CZ_MMCI.collection.LTS#perun.bbmri-eric.eu\"]",
                "ValueType": "json"
              }
            ]
          }
        ]
      CLIENTS_CONFIGURATION_PATH: /config/clients.json
    volumes:
      - ./config:/config:ro
